apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
spec:
  selector:
    matchLabels:
      app: probe
  replicas: 2
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
      - name: probe
        image: "jun06t/probe"
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
          initialDelaySeconds: 10
