apiVersion: v1
kind: Service
metadata:
  name: alive-admin-svc
spec:
  type: NodePort
  ports:
  - name: admin
    port: 3001
    protocol: TCP
    targetPort: 10001
  selector:
    app: alive-service

