apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: golang
          image: jun06t/show-cpus
#          env:
#          - name: GODEBUG
#            value: "scheddetail=1,schedtrace=1000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

