apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: "jun06t/client-side-lb:client"
        imagePullPolicy: Always
        name: client
        env:
        - name: ENDPOINT
          value: "headless-svc:8080"
        - name: GRPC_VERBOSITY
          value: "DEBUG"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "2"
        - name: GRPC_TRACE
          value: "all"
#        - name: GODEBUG
#          value: "http2debug=2"

