apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None
  ports:
  # Actually, no port is needed.
  # but set it because of the following bug.
  # https://github.com/kubernetes/kubernetes/issues/55158
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
